"""added relation one to many

Revision ID: cbfddc4e5fcf
Revises: 
Create Date: 2023-08-17 09:54:00.625025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbfddc4e5fcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_name', sa.String(length=200), nullable=False),
    sa.Column('base_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['base_name'], ['base.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child')
    # ### end Alembic commands ###
